tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "jbangdev/tap"
tap "micronaut-projects/tap"
tap "splieth/swamp"
brew "ack"
brew "awscli"
brew "awsume"
brew "bat"
brew "cdktf"
brew "cmake"
brew "coreutils"
brew "dive"
brew "elixir"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "fnm"
brew "gh"
brew "ghq"
brew "git"
brew "go"
brew "htop"
brew "jq"
brew "kompose"
brew "openjdk"
brew "kotlin"
brew "kubernetes-cli"
brew "kubeval"
brew "mas"
brew "maven"
brew "openjdk@11"
brew "openssl@3"
brew "peco"
brew "pnpm"
brew "podman"
brew "procs"
brew "ripgrep"
brew "rustup-init"
brew "tldr"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "ykman"
brew "youtube-dl"
brew "yq"
brew "aws/tap/aws-sam-cli"
brew "jbangdev/tap/jbang"
brew "splieth/swamp/swamp"
cask "aerial"
cask "bettertouchtool"
cask "cacher"
cask "dbeaver-community"
cask "deepl"
cask "discord"
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "micronaut"
cask "microsoft-teams"
cask "miro"
cask "notion"
cask "raycast"
cask "sensei"
cask "sourcetree"
cask "spotify"
cask "steam"
cask "tableplus"
cask "visual-studio-code"
cask "zoom"
mas "Agenda", id: 1287445660
mas "Disk Speed Test", id: 425264550
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Luminar AI", id: 1541310539
mas "Microsoft Outlook", id: 985367838
mas "Moom", id: 419330170
mas "NordVPN", id: 905953485
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Speedtest", id: 1153157709
mas "Todoist", id: 585829637
mas "World Clock", id: 956377119
mas "Xcode", id: 497799835
mas "Yubico Authenticator", id: 1497506650
